### ISSUE TITLE
Inconsistency between code and comment

### ISSUE THREAD

**Issue by YichiZhang0613** [t28hub/auto-palette#5]
In auto-palette/src/math/number.rs, the comment Panics if `min` is greater than or equal to `max` indicates that the constraint is min < max while the code check min <= max.
```rust
/// # Panics
/// Panics if `min` is greater than or equal to `max`.
#[inline]
#[must_use]
pub fn normalize<T>(value: T, min: T, max: T) -> T
where
    T: FloatNumber,
{
    debug_assert!(min <= max, "min must be less than or equal to max");
    (value - min) / (max - min)
}
```

**Comment by t28hub** [comment]
This issue is fixed in the [commit](https://github.com/t28hub/auto-palette/commit/d1d8e6fe70567cf88380f33c4fe148fe633f545c).
